feat: [AXIMST-344] Copy/paste functionality base
raccoongang/frontend-app-course-authoring pull request #115
Opened 2024-01-16 16:00 UTC by monteri

https://youtrack.raccoongang.com/agiles/104-1224/105-3378?issue=AXIMST-344

2024-01-28 12:58 UTC, PKulkoRaccoonGang requested changes
@monteri The copy functionality looks great! 
Left comments for improvements and bug fixes. 
Please make sure that the waffle flag `contentstore.enable_copy_paste_units` is present in the documentation for testing

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
> +import { copyToClipboard, fetchCourseUnitQuery } from '../../../data/thunk';
```suggestion
import initializeStore from '../../../../store';
import { executeThunk } from '../../../../utils';
import { copyToClipboard, fetchCourseUnitQuery } from '../../../data/thunk';
import { getClipboardUrl, getCourseUnitApiUrl } from '../../../data/api';
import { clipboardUnit, courseUnitIndexMock } from '../../../__mocks__';
import ActionButtons from './ActionButtons';
```

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/i18n/messages/fa_IR.json
> +  "course-authoring.course-unit.xblock.button.copyToClipboard.label": "Copy to clipboard",
[important]: Please return the translation you deleted

> "course-authoring.course-unit.xblock.button.move.label": "Move",

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/course-xblock/CourseXBlock.jsx
> +                  <Dropdown.Item onClick={() => dispatch(copyToClipboard(id))}>
[clarify]: Also now we have two buttons for copying, should it be like this?

**Implementation:**
<img width="370" alt="Screenshot 2024-01-28 at 14 12 54" src="https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/dd21eeba-de7b-4a32-bdf7-70d87817c0c6">

**Design:**
<img width="303" alt="Screenshot 2024-01-28 at 14 15 28" src="https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/7d07fbfa-e298-4d65-abeb-83aa76cc6a87">

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/thunk.js
> +  const POLL_INTERVAL_MS = 1000; // Timeout duration for polling in milliseconds
[question]: If we plan to use notification delay for smoothness and improve the user experience, should we put this constant in the appropriate constants file?

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/thunk.js
> +      dispatch(updateClipboardData(courseSectionVerticalData.userClipboard));
👍

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/thunk.js
> +  const POLL_INTERVAL_MS = 1000; // Timeout duration for polling in milliseconds
[clarify]: After you added a mandatory delay for notifications to show, should I still be able to see the notifications now?

https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/3ef3a6db-37aa-479b-b781-b331f4e76eeb

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
> +    expect(getByTestId('copy-xblock-to-clipboard')).toBeInTheDocument();
[important]: Now you find the button using date-test-id, let's find it using `getByRole` and text content

For example: 
```suggestion
    const copyXBlockBtn = getByRole('button', { name: messages.actionButtonCopyUnitTitle.defaultMessage });
    expect(copyXBlockBtn).toBeInTheDocument();
```

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
> +    const copyToClipboardButton = getByTestId('copy-xblock-to-clipboard');
[fiy]: Do not search by ID for elements that can be found by role :)

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
> +    await act(async () => {
[important]: Please remove the unnecessary act(...) wrapper, `userEvent` is already wrapped in it

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.jsx
> +          data-testid="copy-xblock-to-clipboard"
[important]: don't forget to remove `data-testid` after refactoring the tests

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/sidebar/components/sidebar-footer/ActionButtons.jsx
> +import { copyToClipboard } from '../../../data/thunk';
```suggestion
import { copyToClipboard } from '../../../data/thunk';
import { getCourseUnitData } from '../../../data/selectors';
import messages from '../../messages';
```

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/api.js
> +  const { data } = await getAuthenticatedHttpClient().get(getClipboardUrl());
[optional]:
```suggestion
  const { data } = await getAuthenticatedHttpClient()
     .get(getClipboardUrl());
```

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/api.js
> +  const { data } = await getAuthenticatedHttpClient().post(getClipboardUrl(), { usage_key: usageKey });
[optional]:
```suggestion
  const { data } = await getAuthenticatedHttpClient()
    .post(getClipboardUrl(), { usage_key: usageKey });
```

2024-01-28 12:58 UTC, PKulkoRaccoonGang commented on src/course-unit/data/thunk.js
> +    dispatch(updateQueryPendingStatus(true));
[important]: Currently, the notification about Internet problems does not work as expected (an error message and a message about the lack of Internet connection appear). Note how this works for the functionality of adding a new unit.

https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/18a94a5e-1ee2-4372-a479-135dc0378dc7

2024-01-29 13:58 UTC, monteri commented on src/course-unit/clipboard/useClipboard.jsx
> +import { NOT_XBLOCK_TYPES, STUDIO_CLIPBOARD_CHANNEL } from '../constants';
👍

2024-01-30 11:01 UTC, merged