feat: [AXIMST-166] certificates screen with data
raccoongang/frontend-app-course-authoring pull request #143
Opened 2024-01-31 17:27 UTC by khudym

YT: https://youtrack.raccoongang.com/issue/AXIMST-166

2024-01-31 19:17 UTC, PKulkoRaccoonGang requested changes

2024-01-31 19:17 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-details/CertificateDetails.jsx
> +                variant="primary"
[important]: The primary variant is the default for this component

2024-01-31 19:17 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-details/CertificateDetails.jsx
> +                variant="primary"
[important]: The primary variant is the default for this component

2024-01-31 19:17 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-signatories/signatory/Signatory.jsx
> +            {signatureImagePath && <img src={`${getConfig().STUDIO_BASE_URL}${signatureImagePath}`} alt="signature" className="d-block w-100" />}
[nit]: Let's add a translation for the alt text and try to use Paragon component Image

2024-01-31 19:17 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-signatories/signatory/Signatory.test.jsx
> +    expect(getByText('John Doe')).toBeInTheDocument();
` expect(defaultProps.name).toBeInTheDocument();
`

2024-01-31 19:17 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-signatories/signatory/Signatory.test.jsx
> +    expect(getByText('Director')).toBeInTheDocument();
`expect(defaultProps.title).toBeInTheDocument();`

2024-02-01 13:21 UTC, monteri requested changes
Please, fix lint issues

2024-02-01 13:21 UTC, monteri commented on src/certificates/data/thunks.js
> +      dispatch(hideProcessingNotification());
move to `finally`

2024-02-01 13:21 UTC, monteri commented on src/certificates/data/thunks.js
> +      dispatch(getDataSendErrors(errorData));
Check if this is required

2024-02-01 13:21 UTC, monteri commented on src/certificates/hooks/useCertificates.jsx
> +  }, [hasCertificateModes, certificates]);
```suggestion
useEffect(() => {
  if (!hasCertificateModes) {
    dispatch(setMode(MODE_STATES.NO_MODES));
  } else if (certificates.length === 0) {
    dispatch(setMode(MODE_STATES.NO_CERTIFICATES));
  } else {
    dispatch(setMode(MODE_STATES.VIEW));
  }
}, [hasCertificateModes, certificates]);
```

2024-02-01 13:21 UTC, monteri commented on src/certificates/scss/Certificates.scss
> +    .details-info {
```suggestion
    .certificates__details-info {
```

2024-02-01 13:21 UTC, monteri commented on src/certificates/scss/Certificates.scss
> +    .details-info {
and all classnames below

2024-02-01 13:21 UTC, monteri commented on src/generic/modal-dropzone/useModalDropzone.jsx
> +const useModalDropzone = ({ onChange, onCancel, onClose }) => {
Allow to pass `fileTypes` `Array`

2024-02-01 13:21 UTC, monteri commented on src/generic/modal-dropzone/useModalDropzone.jsx
> +    if (file.type !== 'image/png') {
```suggestion
    if (!fileTypes.includes(file.type)) {
```

2024-02-01 13:21 UTC, monteri commented on src/generic/modal-dropzone/ModalDropzone.test.jsx
> +      fireEvent.change(dropzoneInput, { target: { files: ['test-file.png'] } });
`fireEvent` change to `userEvent`

2024-02-01 13:21 UTC, monteri commented on src/certificates/with-modes-without-certificates/WithModesWithoutCertificates.jsx
> +const WithModesWithoutCertificates = () => {
`EmptyCertificatesWithModes`

2024-02-01 13:21 UTC, monteri commented on src/certificates/Certificates.jsx
> +  [MODE_STATES.VIEW]: CertificatesCards,
```suggestion
  [MODE_STATES.NO_MODES]: CertificateWithoutModes,
  [MODE_STATES.NO_CERTIFICATES]: EmptyCertificatesWithModes,
  [MODE_STATES.CREATE]: CertificateCreate,
  [MODE_STATES.VIEW]: CertificatesCards,
```

2024-02-02 13:26 UTC, closed without merging