feat: [AXIMST-172] Certificates page - certificates delete
raccoongang/frontend-app-course-authoring pull request #150
Opened 2024-02-02 16:06 UTC by khudym

YT: https://youtrack.raccoongang.com/issue/AXIMST-172

2024-02-04 13:42 UTC, PKulkoRaccoonGang requested changes
@khudym Some observations on the alert reporting the absence of the Internet. It seems to me that we need to move this alert down from the modal window (since this is implemented in Legacy).

![telegram-cloud-photo-size-2-5332538752725275834-y](https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/25d97513-9fd1-48cc-8050-49e88b4811b5)


![telegram-cloud-photo-size-2-5332538752725275833-y](https://github.com/raccoongang/frontend-app-course-authoring/assets/93188219/8d5f7b24-5d0b-4468-b015-4ed352d81a10)

2024-02-04 13:42 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-signatories/signatory/Signatory.test.jsx
> +    expect(getByText(`Delete "${defaultProps.name}" from the list of signatories?`)).toBeInTheDocument();
[important]: Please use an [existing](https://github.com/raccoongang/frontend-app-course-authoring/blob/6ef7e35e260f2274f878b1793aab1a78832ebdb2/src/certificates/certificates-card/messages.js#L126) translation. For [example](https://github.com/raccoongang/frontend-app-course-authoring/blob/6ef7e35e260f2274f878b1793aab1a78832ebdb2/src/course-team/info-modal/InfoModal.test.jsx#L63)

2024-02-04 13:42 UTC, PKulkoRaccoonGang commented on src/certificates/confirm-modal/ConfirmModal.jsx
> +const ConfirmModal = ({
[qiestion]: Can we use an already [existing generic component](https://github.com/raccoongang/frontend-app-course-authoring/blob/6ef7e35e260f2274f878b1793aab1a78832ebdb2/src/generic/modal-notification/index.jsx)?

2024-02-05 17:08 UTC, monteri reviewed
LGTM, do fixes, that @PKulkoRaccoonGang proposed in the comments.

For future tasks, consider searching for generics first before implementing own soltion like.

2024-02-07 09:30 UTC, PKulkoRaccoonGang approved these changes

2024-02-07 09:30 UTC, PKulkoRaccoonGang commented on src/certificates/certificates-card/certificate-signatories/signatory/Signatory.test.jsx
> +    expect(getByText(`Delete "${defaultProps.name}" from the list of signatories?`)).toBeInTheDocument();
You have already added a check for this text below. Do we need the legacy version?

2024-02-07 09:30 UTC, PKulkoRaccoonGang commented on src/certificates/scss/Certificates.scss
> +  z-index: 9999;
`  z-index: $zindex-popover;`

2024-02-07 11:27 UTC, GlugovGrGlib approved these changes

2024-02-07 11:28 UTC, merged