feat: [AXIMST-129] Textbooks: Textbook preview
raccoongang/frontend-app-course-authoring pull request #172
Opened 2024-02-17 17:28 UTC by vladislavkeblysh

- Add textbook preview

2024-02-19 13:59 UTC, PKulkoRaccoonGang requested changes

2024-02-19 13:59 UTC, PKulkoRaccoonGang commented on src/textbooks/textbook-card/TextbooksCard.jsx
> +                    onClick={() => onPreviewTextbookClick()}
```suggestion
                    onClick={onPreviewTextbookClick}
```

2024-02-19 14:55 UTC, monteri approved these changes

2024-02-20 10:15 UTC, vladislavkeblysh commented on src/textbooks/textbook-card/TextbooksCard.jsx
> +                    onClick={() => onPreviewTextbookClick()}
Fixed

2024-02-20 11:00 UTC, monteri approved these changes

2024-02-20 11:00 UTC, merged