feat: added Proctoring link
raccoongang/frontend-app-course-authoring pull request #46
Opened 2023-08-08 12:20 UTC by PKulkoRaccoonGang

2023-08-08 14:06 UTC, ruzniaievdm requested changes

2023-08-08 14:06 UTC, ruzniaievdm commented on src/grading-settings/GradingSettings.jsx
> +  getProctoringExamSettingsUrl,
remove it please

2023-08-08 14:06 UTC, ruzniaievdm commented on src/grading-settings/GradingSettings.jsx
> +                  proctoredExamSettingsUrl={proctoringExamSettingsUrl}
please use `gradingSettingsData.mfeProctoredExamSettingsUrl`

2023-08-08 14:06 UTC, ruzniaievdm commented on src/grading-settings/data/selectors.js
> +const getProctoringExamSettingsUrl = (state) => state.gradingSettings.gradingSettings.mfeProctoredExamSettingsUrl;
remove it please

2023-08-08 15:22 UTC, vladislavkeblysh approved these changes

2023-08-09 07:34 UTC, wowkalucky approved these changes

2023-08-09 07:34 UTC, merged