fix: [2U-607] reworked Grading Deadline section
raccoongang/frontend-app-course-authoring pull request #64
Opened 2023-08-22 08:30 UTC by PKulkoRaccoonGang

2023-08-22 17:07 UTC, ruzniaievdm requested changes

2023-08-22 17:07 UTC, ruzniaievdm commented on src/grading-settings/deadline-section/messages.js
> +    defaultMessage: 'Grace period must be specified in HH:MM format.',
please get it from `constants.js` above

2023-08-22 17:07 UTC, ruzniaievdm commented on src/grading-settings/deadline-section/utils.js
> +  const EMPTY_STR = '';
take into account comment above

2023-08-22 17:07 UTC, ruzniaievdm commented on src/grading-settings/deadline-section/utils.js
> +export function timerValidation(inputStr, setShowSavePrompt, setIsError) {
please try something like this
```
export function timerValidation(inputStr, setShowSavePrompt, setIsError) {
  const timePattern = /^\d{2,3}:\d{2}$/;

  const isValid = timePattern.test(inputStr);
  setShowSavePrompt(isValid);
  setIsError(!isValid);

  return isValid;
}
```

2023-08-22 17:07 UTC, ruzniaievdm commented on src/i18n/messages/uk.json
> -  "course-authoring.course-outline.sidebar.section-4.link": "Learn more about content visibility settings",
why did you remove this diff only in this file?

2023-08-23 11:35 UTC, PKulkoRaccoonGang commented on src/grading-settings/deadline-section/index.jsx
> +    const EMPTY_STR = ' ';
These constants were different, now one of them has been removed. Let's leave this constant here, I came up with a more appropriate name for it

2023-08-23 11:35 UTC, closed without merging