feat: Course Outline - Update section card
raccoongang/frontend-app-course-authoring pull request #71
Opened 2023-08-23 13:55 UTC by vladislavkeblysh

- Updated section card and tests

[2u-165](https://youtrack.raccoongang.com/issue/2U-615)

2023-08-25 16:13 UTC, ruzniaievdm requested changes

2023-08-25 16:13 UTC, ruzniaievdm commented on src/course-outline/CourseOutline.jsx
> +                          onClickNewSubsection={null}
```suggestion
                          onClickNewSubsection={() => ({})}
```

2023-08-25 16:24 UTC, ruzniaievdm approved these changes

2023-08-25 16:24 UTC, PKulkoRaccoonGang commented on src/course-outline/section-card/SectionCard.scss
> +  padding: 1rem 1.5rem 1.5rem;
```suggestion
  padding: $spacer 1.5rem 1.5rem;
```

2023-08-25 16:24 UTC, PKulkoRaccoonGang commented on src/course-outline/section-card/SectionCard.scss
> +    margin-top: 1rem;
```suggestion
    margin-top: $spacer;
```

2023-08-25 16:26 UTC, vladislavkeblysh commented on src/course-outline/section-card/SectionCard.scss
> +  padding: 1rem 1.5rem 1.5rem;
Done

2023-08-25 16:27 UTC, vladislavkeblysh commented on src/course-outline/section-card/SectionCard.scss
> +    margin-top: 1rem;
Done

2023-08-25 16:28 UTC, PKulkoRaccoonGang approved these changes

2023-08-28 09:35 UTC, wowkalucky approved these changes
OK.

2023-08-28 09:35 UTC, merged